version: 0.2
env:
  parameter-store:
    SONARQUBE_TOKEN: ${SONARQUBE_TOKEN}
    SONARQUBE_ENDPOINT: ${SONARQUBE_ENDPOINT}
    GITHUB_TOKEN: ${GITHUB_TOKEN}
phases:
  install:
    commands:
      - curl -s -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip -o sonarscanner.zip
      - unzip sonarscanner.zip -d .build
      - export PATH=$PATH:./.build/sonar-scanner-3.3.0.1492-linux/bin
  build:
    commands:
      # - mvn sonar:sonar   -Dsonar.projectKey=java-maven-junit-helloworld   -Dsonar.host.url=${SONARQUBE_ENDPOINT}   -Dsonar.login=${SONARQUBE_TOKEN}
      - export PULL_REQUEST_ID=`echo ${CODEBUILD_SOURCE_VERSION} | sed -e 's/pr\///'`
      # - sonar-scanner -Dsonar.login=${SONARQUBE_TOKEN} -Dsonar.github.oauth=${GITHUB_TOKEN} -Dsonar.github.pullRequest=${PULL_REQUEST_ID} -Dsonar.host.url=${SONARQUBE_ENDPOINT}
      - mvn sonar:sonar -Dsonar.projectKey=sonarqube-test -Dsonar.login=${SONARQUBE_TOKEN} -Dsonar.github.oauth=${GITHUB_TOKEN} -Dsonar.host.url=${SONARQUBE_ENDPOINT}